// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DoctorByCategoryController from "./doctorByCategory_controller.js"
application.register("doctorByCategory", DoctorByCategoryController)

import HelloController from "./hello_controller.js"
application.register("hello", HelloController)

import MakeAppointmentController from "./makeAppointment_controller.js"
application.register("makeAppointment", MakeAppointmentController)

import WriteRecommendationController from "./writeRecommendation_controller.js"
application.register("writeRecommendation", WriteRecommendationController)
